project:
  type: website

website:
  title: "What's The Progress"
  description: "a blog to show projects and progress"
  open-graph: true
  navbar:
    right:
      - about.qmd
      - experiences.qmd
      - icon: github
        href: https://github.com/progressEdd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
